name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        options: 
        - dev1
        - dev2
        - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Show inputs
      run: |
        echo "target: ${{ github.event.inputs.target }}"
        echo "message: ${{ github.event.inputs }}"
        echo "ref ${{ github.ref_name }}"
    - name: Deploy (use environemt secrets)
      run: |
        echo "sss"
